### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Junjun-Xu** [adriaan-vd-graaf/genome_integration#1]
Hi,
I'm sorry to say that I made an error during the installation. Could you help me solve it?
![image](https://user-images.githubusercontent.com/33317454/132812907-41e48e8a-2586-473c-9c93-4b539143995b.png)

There is a question on my gcc? The version of gcc is "gcc (GCC) 6.2.0"
Thanks a lot.
Jun

**Comment by adriaan-vd-graaf** [comment]
Hi Jun,

Thanks for using MR-link! The version that is online now is mostly used as
a development version, and has some very interesting requirements, as I
wanted to use a niche statistical package.
As a quick fix, could you try and install the version of the first release.

https://github.com/adriaan-vd-graaf/genome_integration/releases/tag/v1.0

I'll make sure to fix this issue soon, and do development branches, I think
however that this would be the easiest fix for now.

best wishes, Adriaan

**Comment by Junjun-Xu** [comment]
Hi Adriaan,
Thank you very much for your quick reply, but I still got the same report of error according to your suggestion (genome_integration-1.0.zip). If you have any other suggestions, please tell me. Thanks a lot.
Jun

**Comment by adriaan-vd-graaf** [comment]
Unfortunately, I can't provide a quick fix now, but I hope to give one over
the weekend.

best wishes, Adriaan

**Comment by adriaan-vd-graaf** [comment]
Hi Junjun, 

Sorry for the delay, unfortunately I haven't been able to take the time to fix this issue until now. I believe I've fixed the issue now by removing the dependencies on certain libraries.  Installing on a fresh remote computer fixed the issue.

Could you check if you can install genome_integration now?

best wishes, Adriaan
